name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest with coverage
        run: pytest tests/ --cov=my_calculator --cov-report=xml -v

      - name: Run pylint
        run: pylint my_calculator/ --fail-under=7.0

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: coverage.svg

      - name: Save badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: badge жаңартылды [skip ci]"
          file_pattern: coverage.svg
